### ISSUE TITLE
a question on sharding..

### ISSUE THREAD

**Issue by cosnicolaou** [grailbio/bigslice#16]
I have a large input set in a dynamodb table that I'd like to dump it to a sharded set of output files that support lookups (grailbio/recordio is the underlying format). I'd like to mod shard the original keys so that given a key I know which file to look the key up in. I have a writerfuncs set up to match the number of input shards and ideally I'd like bigslice to invoke the write func for shard n with all and only the mod-sharded values of my input keys. Is there any way to do this? I don't see any guaranteed way of doing so? My alternative of course is to have each writerfunc be able to write all of the sharded output files, but that seems contrary to the writerfunc model. 

I should say that Reshuffle doesn't appear to work as I would expect it to, which would be drive all keys with the same value to the same shard.

Thanks!

**Comment by mariusae** [comment]
This should work with Reshuffle--what are you observing that isn't expected? I'd expect the job you're describing as being expressed like:

```
slice := bigslice.ReaderFunc(nshard, func(shard int, state *state, keys []keytype, vals []valuetype) (n int, err error) {
    // .. scan from dynamodb; store cursor in state.
}
slice = bigslice.Reshuffle(slice)
slice = bigslice.Scan(slice, func(shard int, scan *sliceio.Scanner) error {
    path := fmt.Sprintf("/prefix/shard-%d-of-%d", shard, nshard)
    var (
        key keytype
        value valuetype
    )
    for scan.Scan(&key, value) {
        // write into file
    }
    return scan.Err()
})
```

**Comment by cosnicolaou** [comment]
In the example code below, I would expect shard to be equal to s in all cases... which does not seem to be the case.... notwithstanding that, I was trying to use WriterFunc rather than Scan, and I also need the records sorted which Reshuffle doesn't provide.
```go
slice = bigslice.Map(slice, func(docID string, ....) (int,...) { return  docIDAsNum % numShards, ... })
slice = bigslice.Reshuffle(slice)
slice = bigslice.Scan(slice, func(shard int, scanner *sliceio.Scanner) error {
				var s int
				for scanner.Scan(context.Background(), &s,....) {
					fmt.Printf("%v: %v\n", shard, s)
				}
				return scanner.Err()
			})
```

**Comment by mariusae** [comment]
Ah, yes, Bigslice will hash the integer in this case. If you'd like, you can control this by wrapping the type (e.g., `type hashedInt int`) and use `frame.RegisterOps` to register your own hashing function. 

About sorting, that would be relatively easy to provide. In this case, what would you like them sorted by? Subsequent columns?

**Comment by mariusae** [comment]
(Another idea is to provide a version of reshuffle that lets you pass a function directly to assign shards, since that's usually the only situations in which you'd like to explicitly assign shards.)

**Comment by cosnicolaou** [comment]
but even if it is hashing I would expect the mapping to be consistent, which is also not the case, i.e. it's not as shard 0 always sees value 2, it sees 1 and 2 etc if you see what I mean.

As for sorting, I think just the same as is done for Reduce, i.e. the prefixed columns. Thanks!

**Comment by mariusae** [comment]
> but even if it is hashing I would expect the mapping to be consistent, which is also not the case, i.e. it's not as shard 0 always sees value 2, it sees 1 and 2 etc if you see what I mean.

yes, that's because when the integers are re-hashed there will be collisions; so the invariant that's 
extended is that each key maps onto the same shard...

**Comment by cosnicolaou** [comment]
Providing my own hashing function that is essentially identity does the trick wrt assignment. With sorting I think I'm set. I do think your second suggestion is probably the better overall solution.

**Comment by mariusae** [comment]
Closing this, as I've captured the top-level issue in #17.
