### ISSUE TITLE
Provide user-controlled sharding

### ISSUE THREAD

**Issue by mariusae** [grailbio/bigslice#17]
As outlined in #16, it's often useful to extend fine-grained control of sharding to the user. It can be solved by wrapping integers with an identity hash function, but that seems less than ideal. It might be useful to provide this functionality as part of `bigslice.Reshuffle`.

**Comment by mariusae** [comment]
# Detailed design proposal

Currently Bigslice always uses a standard hash partitioner (based on the prefix value). We can extend slices to provide their own partitioner:

```
type Slice {
   ...
  // Partition partitions the elements in the provided frame into 
  // nshard shards.
  Partition(frame Frame, nshard int, shards []int)
}
```

the default implementation of which is:

```
func Partition(frame Frame, nshard int, shards []int) {
  for i := range shards {
    shards[i] = frame.Hash(i) % nshard
  }
}
```

We can then attach partitioners to slices via a new `bigslice.Partitioned` combiner:

```
func Partitioned(slice Slice, partitioner interface{}) Slice { ... }
```

partitioner is a function that takes a number of shards and a prefix of columns, returning the shard to which the row belongs, e.g.:

```
slice = bigslice.Partitioned(slice, func(nshard int, docId int) int { return docId%nshard })
```

**Comment by mariusae** [comment]
cc: @jcharum @cosnicolaou for API feedback

**Comment by cosnicolaou** [comment]
The API looks sound. How would sorting/ordering work though? I imagine that if you start with n shards and then partition to m, that each input shard could contribute to every output shard.

**Comment by mariusae** [comment]
Yes, it would be a regular shuffle, except with a custom partitioning function (today it's fixed to hash partitioning). Sorting is orthogonal and could be done with another optional argument to Reshuffle.

**Comment by jcharum** [comment]
https://github.com/grailbio/bigslice/commit/b9c0924ffaa59d2662de4c3a32bf90ca99d832b1 addresses this issue. We can consider the ordering separately.
