### ISSUE TITLE
Checksum mismatch on github.com/grailbio/testutil@v0.0.1 

### ISSUE THREAD

**Issue by psampaz** [grailbio/bigslice#2]
Steps to reproduce:

$ git clone https://github.com/grailbio/bigslice
$ cd bigslice 
$ go test

Output of go test::

```
go: downloading github.com/grailbio/testutil v0.0.1
verifying github.com/grailbio/testutil@v0.0.1: checksum mismatch
	downloaded: h1:s6IeIZsZHQZXcUnmEKqz22cSn05QsTH5AwHnrxMRKEs=
	go.sum:     h1:RzGxJO5krJooQGu7pOOgA7RdrwF9L+PTGEIuO3O/M0g=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

Go version:

```
go version go1.13 linux/amd64
```

go env:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ps/.cache/go-build"
GOENV="/home/ps/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ps/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ps/Code/bigslice/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build504681712=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by mariusae** [comment]
Thanks. Can you try again? I've just updated go.{mod,sum}; it works here.

**Comment by psampaz** [comment]
Same error

```
$ git clone https://github.com/grailbio/bigslice.git
Cloning into 'bigslice'...
remote: Enumerating objects: 1507, done.
remote: Counting objects: 100% (1507/1507), done.
remote: Compressing objects: 100% (525/525), done.
remote: Total 1507 (delta 977), reused 1436 (delta 919), pack-reused 0
Receiving objects: 100% (1507/1507), 2.27 MiB | 577.00 KiB/s, done.
Resolving deltas: 100% (977/977), done.

$ cd bigslice/

$ go test
go: downloading github.com/grailbio/testutil v0.0.2-0.20190910222532-7f08e0a97d25
go: downloading github.com/grailbio/bigmachine v0.5.0
go: downloading v.io v0.1.6
go: downloading golang.org/x/sys v0.0.0-20191007154456-ef33b2fb2c41
go: extracting github.com/grailbio/bigmachine v0.5.0
go: downloading golang.org/x/net v0.0.0-20191003171128-d98b1b443823
verifying github.com/grailbio/testutil@v0.0.2-0.20190910222532-7f08e0a97d25: checksum mismatch
	downloaded: h1:GepGiX3NLiA6elFc6q1NgwnBTWjStxOfPLjEcE6eX3g=
	go.sum:     h1:qZeT0HwHiLfLPxZhWTGaHEENWWy7fSBsmwz0N8tbeGo=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by cosnicolaou** [comment]
This is likely because of some changes I made earlier this month to break a circular dependency between testutil, grailbio and yaz's zlibng package and get things working again after the apache.org/thrift package was moved. All very complicated and annoying, but in summary I ended up juggling the release tags to break the dependency. It looks as if @psampaz git pull'ed one of those repos whilst I was in the process of said juggling so picked up the old #. Deleting that go.sum and running go mod tidy should clean things up I think/hope!

**Comment by cosnicolaou** [comment]
I also see this now that I've updated grailbio/base to use v.io 1.7 which in turn is needed to catch up with an api change to gopsutil..

go: extracting v.io v0.1.7
```
verifying github.com/grailbio/testutil@v0.0.1: checksum mismatch
	downloaded: h1:s6IeIZsZHQZXcUnmEKqz22cSn05QsTH5AwHnrxMRKEs=
	go.sum:     h1:RzGxJO5krJooQGu7pOOgA7RdrwF9L+PTGEIuO3O/M0g=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by cosnicolaou** [comment]
Removing go.sum and go mod tidy'ing gets rid of the above error, but instead I now have the following:
```
go build ./...
build github.com/grailbio/base/cmd/grail-fuse: cannot load github.com/hanwen/go-fuse/fs: module github.com/hanwen/go-fuse@latest (v1.0.0) found, but does not contain package github.com/hanwen/go-fuse/fs
```

**Comment by cosnicolaou** [comment]
Note that the original grailbio/base go.sum contained the following:
```
github.com/klauspost/compress v1.8.1/go.mod h1:RyIbtBH6LamlWaDj8nUwkbUhJ87Yi3uG0guNDohfE1A=
github.com/klauspost/compress v1.8.4 h1:kecSN5NBXafCCyyzBGF3lsKqPbU1HdtG7usSTs3rE3I=
github.com/klauspost/compress v1.8.4/go.mod h1:RyIbtBH6LamlWaDj8nUwkbUhJ87Yi3uG0guNDohfE1A=
```
Note that the checksums for 1.8.1 and 1.8.4 are the same. Removing the go.sum does fix the problem, but it comes back if you remove the pkgs/... subdirectory. This makes me think that tagging got messed up for that repo. I updated to 1.8.5 and that fixes the problem.

The fuse problem is puzzling, since I don't understand how it could have ever worked. That is, the v1.0.0 code on github does not include a fuse/fs, so the error makes total sense, but I just don't see how this ever worked. I've updated the grailbio/base package appropriately.

**Comment by mariusae** [comment]
Continuing from #3:

I pushed a change that did the same (rm go.sum; go mod tidy).

Locally, this seems to work:
```
bigslice% go mod verify
all modules verified
```

It also appears to work in travis for Go 1.12.x: https://travis-ci.org/grailbio/bigslice/jobs/595702076, but not Go 1.13.x: https://travis-ci.org/grailbio/bigslice/jobs/595702077

Does anyone have any idea why this might be?

**Comment by mariusae** [comment]
@siddharthab and I were experimenting with this, and it appears there is some issue with the grailbio/testutil package that causes the Go proxy, Sum database, or the combination of the two to do the wrong thing with go1.13.

Everything works when these are turned off:
```
GOPROXY=direct 
GOSUMDB=off 
```

I've done this for Travis CI for now (https://github.com/grailbio/bigslice/commit/2648d4bb4324e7a7cfbacb2bc4bbf8a06bb6bd3d) but we're still hunting down the underlying issue.

**Comment by mariusae** [comment]
Update: until we can resolve this more properly, I have removed the checksum for testutil from go.sum. This will at least make it work, and, with go1.13, it will still use the SUMDB.

**Comment by pbrit** [comment]
I believe you were/are affected by https://github.com/golang/go/issues/38941.

#### Workaround:
```bash
$ export GIT_LFS_SKIP_SMUDGE=1
```
