### ISSUE TITLE
exec: add some form of log.Flush.Sync mechanism

### ISSUE THREAD

**Issue by cosnicolaou** [grailbio/bigslice#23]
As called out in PR #21, it appears that the last few lines of log output can be lost when an error is reported to the master. The exact reason is not clear, but adding a sleep worker.Init helps. Investigate this and provide a more robust mechanism to ensure that log lines are not lost.

**Comment by mariusae** [comment]
To help diagnose the underlying problem: does this happen when the master itself is about to die?  (In which case, it's probably just a pretty straightforward race..)

**Comment by cosnicolaou** [comment]
I think these posts [part-1](https://coreos.com/blog/eliminating-journald-delays-part-1.html) and [part-2]( https://coreos.com/blog/eliminating-journald-delays-part-2.html) may shed some light on what's going and it's not particularly surprising. I suspect that when the a process dies, fsync gets called, and fsync can take a while, this all makes sense given that journald maintains durable logs.

To answer your question, it seems to happen when an error is encountered that causes the worker to exit, but that's not a panic. The master is not about to die. The master is exiting before journald makes the output available. Waiting one second is just a band aid that worked for my particular use case, but given the stats in the the posts above then 1 second is not going to work for many cases.

The only 'hack' I can see is to use journalctl --rotate to force a log rotation and to not end the tail until that's complete. Do you and Jerry agree? If so, I can give that a go. LMK.

**Comment by mariusae** [comment]
We already [delay shutting the machine down](https://github.com/grailbio/bigmachine/blob/f5da018e7b712944923a70b1142b0ea7d413b905/ec2system/ec2machine.go#L786) for the same reason: giving it a chance to flush log output.

If the problem is that the master is exiting before log output is available, then it seems to me that the best solution here is to delay process exit until all logs are flushed. As you point out this is more subtle than is ideal.

One possibility is to have the worker emit a marker log message at the end, which we then parse in the log tailer. We know that the process is fully shut down once we encounter the marker.

**Comment by jcharum** [comment]
If I understand correctly, the marker would require (roughly):

1. Adding a marker line above the [https://github.com/grailbio/bigmachine/blob/f5da018e7b712944923a70b1142b0ea7d413b905/ec2system/ec2machine.go#L786](sleep).
2. Amending `Tail` to inspect the log as it passes through to check for the marker (or some timeout from machine stoppage in case something else goes wrong(?)).
3. Synchronizing on `Shutdown`(?).

That seems reasonable to me.

**Comment by cosnicolaou** [comment]
This seems fragile since we would need to ensure that every code path appends the 'magic' string. How about just running journalctl rotate and exiting after it's done - it guarantees to wait for all logs to be rotated and hence they must be flushed? The master would simple run this command via ssh and then exit.

**Comment by mariusae** [comment]
> This seems fragile since we would need to ensure that every code path appends the 'magic' string. How about just running journalctl rotate and exiting after it's done - it guarantees to wait for all logs to be rotated and hence they must be flushed? The master would simple run this command via ssh and then exit.

But this still has a race: even though the logs are flushed, it does not mean that they have necessarily been propagated to the master. Having a marker message would act as a proper sequencer...

**Comment by mariusae** [comment]
> This seems fragile since we would need to ensure that every code path appends the 'magic' string.

I don't think it needs to be fragile: we can add the magic string in the [startup script](https://github.com/grailbio/bigmachine/blob/f5da018e7b712944923a70b1142b0ea7d413b905/ec2system/ec2machine.go#L785), which will always run after process exit.

**Comment by cosnicolaou** [comment]
so I dug into this a bit more and it seems that my original understanding of what's going on is mostly wrong and that it's the master that's exiting without waiting for the output to be read. I hope to have PR out tomorrow that has some form of explicit sync along the above lines.

**Comment by cosnicolaou** [comment]
So there are a number of 'issues' that I'd like some help with to come up as clean/simple a solution as possible. But I've verified that output is lost and that waiting for them does catch it so this is worth fixing and that two other folks here have run into the same problem. 

The challenge is how to fit the synchronisation into the current code base across bigmachine and bigslice. There are two options that I've considered:
1. have the session shutdown perform the synchronisation on shutdown
2. have finer grained synchronisation where each worker.Run invocation results in sychronised using some magic output from worker.Run (which is easy enough via a defer via worker.Run). 

I've currently discounted 2, because it seems strictly more complicated if my understanding of how bigslice can be used is correct. Namely, a single ec2 machine can host multiple runs, possibly concurrently, I say this because session.Run can be so used. Now, today's implementation may not do so, but it seems that is an implementation detail and not something to be committed to. That would clearly make synchronisation harder. However, the code structure also fights it today, in that the log is tailed in bigmachine and not bigslice, so it would need to be extended out. This is also a consideration for 1, see below,

With that in hand, I looked at option 1 more completely, but it has the following challenge,
namely Marius' suggestion of putting a marker in the output from the startup script is undone because $bin never actually exits.  I can see two ways of getting $bin to exit:
  - change the API to system.Shutdown (so that it accepts a Machine) and then have it invoke
    journalctl -s INT TERM -u bootmachine. This would allow bigmachine.B.Shutdown to wait
    for the ssh stream reading from journalctl to be closed.
  - arrange for $bin to exit somehow, this seems to require the bigslice executor to support an
    exit RPC and have that be invoked by bigslice. This would require a higher shutdown 
   synchronisation mechanism and changes to bigmachine since it currently captures the journald
   output internally and copy's it to stderr.

So on-balance, I think making system.Shutdown work is the way to go. The user observed behaviour would be that the trailing log output would be displayed when the shutdown method returned by NewSession is invoked, which seems fine since we're trying to catch errors that would otherwise be missed.

Thoughts?

**Comment by jcharum** [comment]
Would it be sufficient to:

1. Add a `(*bigmachine.Supervisor).Shutdown` method that exits the `bigmachine` process.  (If there's something that can be done to help log flushing, do it (e.g. sync stdout).
2. Modify `(*ec2system.System).Shutdown` to call `Supervisor.Shutdown` on all live machines.
3. Modify `(*ec2system.System).Shutdown` to wait for all outstanding tails.  They will all return when the machines die and the ssh sessions end.

?

**Comment by mariusae** [comment]
I don't think we even need Shutdown. We could decouple the behavior:

1. Add `(*bigmachine.Supervisor).Write(ctx, filename, io.Reader)`.
2. On Bigslice shutdown, write shutdown marker to `/dev/stderr` to all machines under management.
3. Wait until all tokens received (or timeout expires, with a warning).

(These steps could also be codified via a Bigmachine API, like `(*B).Sync`--seems generally useful.)

I think it's useful to decouple these: this allows for a more general syncing strategy, and we'll want to modify Bigmachine in the future to reuse existing instances.

**Comment by cosnicolaou** [comment]
This still requires some way for bigslice to see the message in the log output, which requires changing how bigmachine handles the log output so that it can be forwarded to bigslice. This is fine, but I presume we'd want to preserve the old behaviour since there may be other dependencies on it.

The advantage to the scheme I outline is that it's self contained to bigmachine. I don't think it prejudices any more granular syncing since all it does is a) implement shutdown and b) wait for the shutdown to take effect. Jerry's suggestion is essentially the same.

**Comment by cosnicolaou** [comment]
Here's a prototype [PR](https://github.com/grailbio/bigmachine/pulls/22) for bigmachine.

**Comment by mariusae** [comment]
I think shutdown is fine for now, but we may want to change it in the future to pull out a "Sync" method (which of course could be called during shutdown). The reason is that I think we'll want to modify Bigmachine in the future to be able to reuse instances, and so keeping them around for a little while is useful.

**Comment by cosnicolaou** [comment]
Sure, that sounds good. I'm going to cross link this issue from bigmachine and the PR there.
