### ISSUE TITLE
ReaderFunc for multiple files..

### ISSUE THREAD

**Issue by cosnicolaou** [grailbio/bigslice#6]
I would expect a ReaderFunc created with 2 shards, one for each of two files, to read the two files concurrently. However, it seems that they are read sequentially, at least when run in local mode.
```
slice = bigslice.ReaderFunc(len(files), NewReaderFunc(files))
....
```
where `NewReaderFunc` looks like:
```go
func NewReaderFunc(filenames []string) interface{} {
	type state struct {}
	return func(shard int, state *state, entities []wikientities.Entity) (n int, err error) {
                ....
		if state.Scanner == nil {
		....
			fmt.Printf("processing: shard: %v file: %v\n", shard, filenames[shard])

		}
.....
```

is this expected?

**Comment by yasushi-saito** [comment]
I think you have to set the parallelism to be >1 explicitly even for the local executor. E.g., -bigslice.parallelism=10

**Comment by cosnicolaou** [comment]
well, I have no such flag so I suspect that's internal to GRAIL. The parallelism is set to 1024 in the profile or bigslice. I can manipulate the parameters via bigslice-set and profiledump reflects that, so I presume the parallelism value is not being picked up by bigslice internally. I'll investigate that - thanks for the pointer!

```
go run . stats --profiledump
param bigmachine/ec2system (
	diskspace = 200 // the amount of (root) disk space to allocate
	sshkey = "" // comma-separated list of ssh keys to be installed
	instance-profile = "" // the instance profile with which to launch new instances
	dataspace = 0 // the amount of scratch/data space to allocate
	security-group = "" // the security group with which new instances are launched
	binary = "https://grail-public-bin.s3-us-west-2.amazonaws.com/linux/amd64/ec2boot0.3" // the bootstrap bigmachine binary with which machines are launched
	ondemand = false // use on-demand instances
	ami = "ami-4296ec3a" // AMI to bootstrap
	aws = aws // AWS configuration for all EC2 calls
	instance = "m3.medium" // instance type to allocate
	username = "" // user name for tagging purposes
)

param bigmachine/neeva-ec2 (
	diskspace = 200 // the amount of (root) disk space to allocate
	sshkeys = "" // comma-separated list of ssh keys to be installed
	instance = "m3.medium" // instance type to allocate
	ami = "ami-4296ec3a" // AMI to bootstrap
	instance-profile = "" // the instance profile with which to launch new instances
	subnet = "" // the subnet within new instances are launched
	dataspace = 0 // the amount of scratch/data space to allocate
	ondemand = false // use on-demand instances
	security-groups = "" // comma separated list of security group with which new instances are launched
	username = "" // user name for tagging purposes
	binary = "https://grail-public-bin.s3-us-west-2.amazonaws.com/linux/amd64/ec2boot0.3" // the bootstrap bigmachine binary with which machines are launched
)

instance bigmachine/system bigmachine/local

param bigslice (
	max-load = 0.95 // per-machine maximum load
	parallelism = 1024 // allowable parallelism for the job
	system = bigmachine/neeva-ec2 // the bigmachine system used for job execution
)

param http addr = ":3333" // the address used for serving http
```

**Comment by cosnicolaou** [comment]
I can now see that the local case is handled differently to the remote. I'm going to work up an entirely flag based config and send that out for review. This should make it easier for other users to integrate bigslice into their workflows. Thanks again for the pointer!

**Comment by mariusae** [comment]
The parallelism argument is the maximum allowable parallelism. Are you running this on a single-cpu machine? You may need to decrease the load factor if you want Bigslice to pack more concurrent tasks.

**Comment by mariusae** [comment]
> I can now see that the local case is handled differently to the remote. I'm going to work up an entirely flag based config and send that out for review. This should make it easier for other users to integrate bigslice into their workflows. Thanks again for the pointer!

The point of the config/profile was exactly this... to make it simple to configure and use Bigslice without much ado. I'm not against a flags-based alternative, but I think that it is ultimately more cumbersome (it means you always have to run your job with the right arguments, or hard-code these in code; the goal of using profiles was to have a central place where this configuration is stored and modified). Also, in the case where you have your own infrastructure for storing and retrieving configuration (e.g., yaml files, etc.), you could easily use the low-level APIs provided by bigmachine and bigslice to construct a session that's appropriate for the environment.

All this to say that I'm not sure a flags-based approach should be the default way of doing things. Maybe there are ways we can change how config works to better accommodate the issues you're running into?

**Comment by cosnicolaou** [comment]
ok, let me see what I do to make it easier/more obvious to integrate with other setups. Now that I have all of the pieces working it should be clearer what to do.
