### ISSUE TITLE
bigslice run: command-line arguments parsing bug

### ISSUE THREAD

**Issue by bereal** [grailbio/bigslice#91]
When I run the example from the docs:

    GO111MODULE=on bigslice run shake.go -local

it returns:

    bigslice: exec: "-local": executable file not found in $PATH

Added some logging to trace the problem, it turns out that `bigslicecmd.Run` receives only `[-local]` as `args`. There seems to be a bug in `cmd/bigslice/run.go`.

**Comment by jcharum** [comment]
@bereal: I think this should be fixed now. Let me know if it works for you, and feel free to file more issues from any problems or friction you encounter. Thanks!

**Comment by bereal** [comment]
@jcharum It works now, than you!
